#!/bin/bash
#$ -S /bin/bash
matlab -nodesktop -nodisplay -nojvm -nosplash -r  "cd /home/grad/trgao10/Work/MATLAB/cPdist/; path(genpath('/home/grad/trgao10/Work/MATLAB/cPdist/utils/'), path); flatten_ongrid ../DATA/PNAS/meshes/j18_sas.off /home/grad/trgao10/Work/MATLAB/cPdist/sample/j18.mat; exit; "